In [1]:
import pandas as pd
import io
from io import StringIO

READ THE CSV AND PERFORM BASIC DATA CLEANING

In [3]:
df_01 = pd.read_csv("Rural/RA/RA2016DF.csv")
#print(df_01.count())
print(df_01)
#drop the null rows
df_01 = df_01.dropna()
print(df_01.count())
print(df_01['Site Name'].unique())

      Unnamed: 0         Site Name        Date  DMean PM10 PM10 Units  \
0              0  Millbrook School   8/27/2016         7.0   ug/m3 SC
1              1  Millbrook School   8/28/2016         7.0   ug/m3 SC
2              2  Millbrook School   8/28/2016        15.0   ug/m3 SC
3              3  Millbrook School   8/28/2016        15.0   ug/m3 SC
4              4  Millbrook School    9/1/2016        15.0   ug/m3 SC
...          ...               ...         ...         ...        ...
1046        1046        Triple Oak  12/15/2016         NaN        NaN
1047        1047        Triple Oak  12/16/2016         NaN        NaN
1048        1048        Triple Oak  12/17/2016         NaN        NaN
1049        1049        Triple Oak  12/18/2016         NaN        NaN
1050        1050        Triple Oak  12/19/2016         NaN        NaN

      PM10 AQI        Lat        Lng  DMax NO2 NO2 Units  NO2 AQI  DMax Ozone  \
0          6.0  35.856111 -78.574167       8.0       ppb      8.0       0.050
1          6.0  35.856111 -78.574167       2.0       ppb      2.0       0.047
2         14.0  35.856111 -78.574167       2.0       ppb      2.0       0.047
3         14.0  35.856111 -78.574167       2.0       ppb      2.0       0.047
4         14.0  35.856111 -78.574167      13.0       ppb     12.0       0.044
...        ...        ...        ...       ...       ...      ...         ...
1046       NaN        NaN        NaN       NaN       NaN      NaN         NaN
1047       NaN        NaN        NaN       NaN       NaN      NaN         NaN
1048       NaN        NaN        NaN       NaN       NaN      NaN         NaN
1049       NaN        NaN        NaN       NaN       NaN      NaN         NaN
1050       NaN        NaN        NaN       NaN       NaN      NaN         NaN

     Ozone Units  Ozone AQI  DMax SO2 SO2 Units  SO2 AQI  DMax CO CO Units  \
0            ppm       46.0       0.3       ppb      0.0      0.3      ppm
1            ppm       44.0       0.2       ppb      0.0      0.2      ppm
2            ppm       44.0       0.2       ppb      0.0      0.2      ppm
3            ppm       44.0       0.2       ppb      0.0      0.2      ppm
4            ppm       41.0       0.6       ppb      0.0      NaN      NaN
...          ...        ...       ...       ...      ...      ...      ...
1046         NaN        NaN       NaN       NaN      NaN      0.6      ppm
1047         NaN        NaN       NaN       NaN      NaN      0.3      ppm
1048         NaN        NaN       NaN       NaN      NaN      0.5      ppm
1049         NaN        NaN       NaN       NaN      NaN      0.5      ppm
1050         NaN        NaN       NaN       NaN      NaN      0.3      ppm

      CO AQI
0        3.0
1        2.0
2        2.0
3        2.0
4        NaN
...      ...
1046     7.0
1047     3.0
1048     6.0
1049     6.0
1050     3.0

[1051 rows x 20 columns]
Unnamed: 0     264
Site Name      264
Date           264
DMean PM10     264
PM10 Units     264
PM10 AQI       264
Lat            264
Lng            264
DMax NO2       264
NO2 Units      264
NO2 AQI        264
DMax Ozone     264
Ozone Units    264
Ozone AQI      264
DMax SO2       264
SO2 Units      264
SO2 AQI        264
DMax CO        264
CO Units       264
CO AQI         264
dtype: int64
['Millbrook School']

In [4]:
#print(df_01.head())
#pd.read_csv(io.StringIO(df_01.to_csv(index=False)))
test_df=df_01.iloc[:,1:]
test_df

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Millbrook School,8/27/2016,7.0,ug/m3 SC,6.0,35.856111,-78.574167,8.0,ppb,8.0,0.050,ppm,46.0,0.3,ppb,0.0,0.3,ppm,3.0
1,Millbrook School,8/28/2016,7.0,ug/m3 SC,6.0,35.856111,-78.574167,2.0,ppb,2.0,0.047,ppm,44.0,0.2,ppb,0.0,0.2,ppm,2.0
2,Millbrook School,8/28/2016,15.0,ug/m3 SC,14.0,35.856111,-78.574167,2.0,ppb,2.0,0.047,ppm,44.0,0.2,ppb,0.0,0.2,ppm,2.0
3,Millbrook School,8/28/2016,15.0,ug/m3 SC,14.0,35.856111,-78.574167,2.0,ppb,2.0,0.047,ppm,44.0,0.2,ppb,0.0,0.2,ppm,2.0
5,Millbrook School,9/2/2016,9.0,ug/m3 SC,8.0,35.856111,-78.574167,6.7,ppb,6.0,0.029,ppm,27.0,0.2,ppb,0.0,0.2,ppm,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Millbrook School,9/6/2016,14.0,ug/m3 SC,13.0,35.856111,-78.574167,20.6,ppb,19.0,0.059,ppm,64.0,0.8,ppb,0.0,0.4,ppm,5.0
296,Millbrook School,9/9/2016,23.0,ug/m3 SC,21.0,35.856111,-78.574167,15.5,ppb,14.0,0.062,ppm,74.0,0.5,ppb,0.0,0.3,ppm,3.0
297,Millbrook School,9/9/2016,23.0,ug/m3 SC,21.0,35.856111,-78.574167,15.5,ppb,14.0,0.062,ppm,74.0,0.5,ppb,0.0,0.3,ppm,3.0
298,Millbrook School,9/21/2016,4.0,ug/m3 SC,4.0,35.856111,-78.574167,2.5,ppb,2.0,0.023,ppm,21.0,0.2,ppb,0.0,0.1,ppm,1.0
299,Millbrook School,9/21/2016,3.0,ug/m3 SC,3.0,35.856111,-78.574167,2.5,ppb,2.0,0.023,ppm,21.0,0.2,ppb,0.0,0.1,ppm,1.0

In [5]:
df_02 = pd.read_csv("Rural/RA/RA2018DF.csv")
#print(df_02.count())
#drop the null rows
df_02 = df_02.dropna()
#print(df_02['Site Name'].unique())

In [6]:
#print(df_02.head())
#pd.read_csv(io.StringIO(df_01.to_csv(index=False)))
test2_df=df_02.iloc[:,1:]
test2_df

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Millbrook School,1/1/2018,7.0,ug/m3 SC,6.0,35.856111,-78.574167,7.2,ppb,7.0,0.037,ppm,34.0,2.0,ppb,3.0,0.2,ppm,2.0
1,Millbrook School,1/2/2018,12.0,ug/m3 SC,11.0,35.856111,-78.574167,33.6,ppb,31.0,0.034,ppm,31.0,1.8,ppb,1.0,0.7,ppm,8.0
2,Millbrook School,1/3/2018,20.0,ug/m3 SC,19.0,35.856111,-78.574167,30.3,ppb,28.0,0.032,ppm,30.0,2.5,ppb,3.0,0.9,ppm,10.0
3,Millbrook School,1/4/2018,13.0,ug/m3 SC,12.0,35.856111,-78.574167,5.4,ppb,5.0,0.035,ppm,32.0,1.9,ppb,1.0,0.2,ppm,2.0
4,Millbrook School,1/5/2018,12.0,ug/m3 SC,11.0,35.856111,-78.574167,18.2,ppb,17.0,0.036,ppm,33.0,1.3,ppb,1.0,0.2,ppm,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,Millbrook School,7/28/2018,18.0,ug/m3 SC,17.0,35.856111,-78.574167,8.0,ppb,8.0,0.046,ppm,43.0,0.1,ppb,0.0,0.3,ppm,3.0
582,Millbrook School,7/29/2018,16.0,ug/m3 SC,15.0,35.856111,-78.574167,4.8,ppb,4.0,0.040,ppm,37.0,0.1,ppb,0.0,0.3,ppm,3.0
583,Millbrook School,7/30/2018,12.0,ug/m3 SC,11.0,35.856111,-78.574167,4.2,ppb,4.0,0.031,ppm,29.0,0.1,ppb,0.0,0.2,ppm,2.0
584,Millbrook School,7/31/2018,16.0,ug/m3 SC,15.0,35.856111,-78.574167,5.2,ppb,5.0,0.034,ppm,31.0,0.0,ppb,0.0,0.2,ppm,2.0
587,Millbrook School,8/3/2018,13.0,ug/m3 SC,12.0,35.856111,-78.574167,6.0,ppb,6.0,0.020,ppm,19.0,0.0,ppb,0.0,0.2,ppm,2.0

In [8]:
df_03 = pd.read_csv("Rural/RA/RA2020DF.csv")
#print(df_01.count())
#drop the null rows
df_03 = df_03.dropna()
print(df_03['Site Name'].unique())

['Millbrook School']

In [9]:
#print(df_03.head())
#pd.read_csv(io.StringIO(df_01.to_csv(index=False)))
test3_df=df_03.iloc[:,1:]
test3_df

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
40,Millbrook School,1/21/2020,6.0,ug/m3 SC,6.0,35.856111,-78.574167,6.4,ppb,6.0,0.040,ppm,37.0,1.3,ppb,1.0,0.2,ppm,2.0
41,Millbrook School,1/21/2020,7.0,ug/m3 SC,6.0,35.856111,-78.574167,6.4,ppb,6.0,0.040,ppm,37.0,1.3,ppb,1.0,0.2,ppm,2.0
42,Millbrook School,1/22/2020,10.0,ug/m3 SC,9.0,35.856111,-78.574167,13.6,ppb,12.0,0.037,ppm,34.0,1.7,ppb,1.0,0.3,ppm,3.0
43,Millbrook School,1/22/2020,12.0,ug/m3 SC,11.0,35.856111,-78.574167,13.6,ppb,12.0,0.037,ppm,34.0,1.7,ppb,1.0,0.3,ppm,3.0
44,Millbrook School,1/23/2020,14.0,ug/m3 SC,13.0,35.856111,-78.574167,13.8,ppb,12.0,0.031,ppm,29.0,0.5,ppb,0.0,0.3,ppm,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,Millbrook School,3/30/2020,12.0,ug/m3 SC,11.0,35.856111,-78.574167,3.7,ppb,3.0,0.050,ppm,46.0,0.1,ppb,0.0,0.2,ppm,2.0
694,Millbrook School,3/31/2020,11.0,ug/m3 SC,10.0,35.856111,-78.574167,2.9,ppb,2.0,0.034,ppm,31.0,0.7,ppb,0.0,0.2,ppm,2.0
695,Millbrook School,4/1/2020,5.0,ug/m3 SC,5.0,35.856111,-78.574167,6.2,ppb,6.0,0.040,ppm,37.0,0.1,ppb,0.0,0.2,ppm,2.0
696,Millbrook School,4/2/2020,8.0,ug/m3 SC,7.0,35.856111,-78.574167,3.3,ppb,3.0,0.044,ppm,41.0,0.3,ppb,0.0,0.2,ppm,2.0
697,Millbrook School,4/3/2020,9.0,ug/m3 SC,8.0,35.856111,-78.574167,6.2,ppb,6.0,0.050,ppm,46.0,0.3,ppb,0.0,0.2,ppm,2.0

In [10]:
AllData=pd.DataFrame()
AllData=AllData.append(test_df)

In [11]:
AllData=AllData.append(test2_df)

In [12]:
AllData=AllData.append(test3_df)

In [14]:
AllData.to_csv("Rural/RA/RAMerged.csv")

In [15]:
AllData

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Millbrook School,8/27/2016,7.0,ug/m3 SC,6.0,35.856111,-78.574167,8.0,ppb,8.0,0.050,ppm,46.0,0.3,ppb,0.0,0.3,ppm,3.0
1,Millbrook School,8/28/2016,7.0,ug/m3 SC,6.0,35.856111,-78.574167,2.0,ppb,2.0,0.047,ppm,44.0,0.2,ppb,0.0,0.2,ppm,2.0
2,Millbrook School,8/28/2016,15.0,ug/m3 SC,14.0,35.856111,-78.574167,2.0,ppb,2.0,0.047,ppm,44.0,0.2,ppb,0.0,0.2,ppm,2.0
3,Millbrook School,8/28/2016,15.0,ug/m3 SC,14.0,35.856111,-78.574167,2.0,ppb,2.0,0.047,ppm,44.0,0.2,ppb,0.0,0.2,ppm,2.0
5,Millbrook School,9/2/2016,9.0,ug/m3 SC,8.0,35.856111,-78.574167,6.7,ppb,6.0,0.029,ppm,27.0,0.2,ppb,0.0,0.2,ppm,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693,Millbrook School,3/30/2020,12.0,ug/m3 SC,11.0,35.856111,-78.574167,3.7,ppb,3.0,0.050,ppm,46.0,0.1,ppb,0.0,0.2,ppm,2.0
694,Millbrook School,3/31/2020,11.0,ug/m3 SC,10.0,35.856111,-78.574167,2.9,ppb,2.0,0.034,ppm,31.0,0.7,ppb,0.0,0.2,ppm,2.0
695,Millbrook School,4/1/2020,5.0,ug/m3 SC,5.0,35.856111,-78.574167,6.2,ppb,6.0,0.040,ppm,37.0,0.1,ppb,0.0,0.2,ppm,2.0
696,Millbrook School,4/2/2020,8.0,ug/m3 SC,7.0,35.856111,-78.574167,3.3,ppb,3.0,0.044,ppm,41.0,0.3,ppb,0.0,0.2,ppm,2.0
697,Millbrook School,4/3/2020,9.0,ug/m3 SC,8.0,35.856111,-78.574167,6.2,ppb,6.0,0.050,ppm,46.0,0.3,ppb,0.0,0.2,ppm,2.0