In [1]:
import pandas as pd

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("DataSets/Daily Data EPA/CO-CarbonMonoxide/2016-Cheyenne-CO.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,Date,Source,Site ID,POC,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,AQS_PARAMETER_CODE,AQS_PARAMETER_DESC,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE
0,1/2/2016,AQS,560210100,1,0.1,ppm,1,Cheyenne NCore,24,100,42101,Carbon monoxide,16940,"Cheyenne, WY",56,Wyoming,21,Laramie,41.182227,-104.778334
1,1/3/2016,AQS,560210100,1,0.2,ppm,2,Cheyenne NCore,24,100,42101,Carbon monoxide,16940,"Cheyenne, WY",56,Wyoming,21,Laramie,41.182227,-104.778334
2,1/4/2016,AQS,560210100,1,0.2,ppm,2,Cheyenne NCore,24,100,42101,Carbon monoxide,16940,"Cheyenne, WY",56,Wyoming,21,Laramie,41.182227,-104.778334
3,1/5/2016,AQS,560210100,1,0.2,ppm,2,Cheyenne NCore,24,100,42101,Carbon monoxide,16940,"Cheyenne, WY",56,Wyoming,21,Laramie,41.182227,-104.778334
4,1/6/2016,AQS,560210100,1,0.2,ppm,2,Cheyenne NCore,24,100,42101,Carbon monoxide,16940,"Cheyenne, WY",56,Wyoming,21,Laramie,41.182227,-104.778334