In [1]:
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

2016 Data

In [2]:
#files to load for 2016
ElPaso_CO_2016 = "CO-CarbonMonoxide/2016-ElPaso-CO.csv"
ElPaso_NO_2016 = "NitrogenDioxide/2016-ElPaso-NO2.csv"
ElPaso_O_2016 = "Ozone/2016-ElPaso-Ozone.csv"
ElPaso_PB_2016 = "PB-Lead/2016-ElPaso-PB.csv"
ElPaso_PM_2016 = "PM-ParticulateMatter/2016-ElPaso-PM10.csv"
ElPaso_SO_2016 = "SulfurDioxide/2016-ElPaso-SO2.csv"

#Read files into Pandas dataframe

df_2016_CO = pd.read_csv(ElPaso_CO_2016)
df_2016_NO = pd.read_csv(ElPaso_NO_2016)
df_2016_O = pd.read_csv(ElPaso_O_2016)
df_2016_PB = pd.read_csv(ElPaso_PB_2016)
df_2016_PM = pd.read_csv(ElPaso_PM_2016)
df_2016_SO = pd.read_csv(ElPaso_SO_2016)


df_2016_PM=df_2016_PM[['Site Name','Date','Daily Mean PM10 Concentration','UNITS','DAILY_AQI_VALUE', 'SITE_LATITUDE','SITE_LONGITUDE' ]]

df_2016_CO=df_2016_CO[['Site Name','Date','Daily Max 8-hour CO Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_NO=df_2016_NO[['Site Name','Date','Daily Max 1-hour NO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_O=df_2016_O[['Site Name','Date','Daily Max 8-hour Ozone Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_SO=df_2016_SO[['Site Name','Date','Daily Max 1-hour SO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_PB=df_2016_PB[['Site Name','Date','Daily Mean Pb Concentration','UNITS','DAILY_AQI_VALUE']]


df_2016_PM

,Site Name,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,SITE_LATITUDE,SITE_LONGITUDE
0,Ivanhoe,10/27/2016,16,ug/m3 SC,15,31.785769,-106.323578
1,Ivanhoe,11/2/2016,13,ug/m3 SC,12,31.785769,-106.323578
2,Ivanhoe,11/8/2016,7,ug/m3 SC,6,31.785769,-106.323578
3,Ivanhoe,11/14/2016,25,ug/m3 SC,23,31.785769,-106.323578
4,Ivanhoe,11/20/2016,18,ug/m3 SC,17,31.785769,-106.323578
...,...,...,...,...,...,...,...
147,Ojo De Agua,10/27/2016,27,ug/m3 SC,25,31.862470,-106.547300
148,Ojo De Agua,11/8/2016,10,ug/m3 SC,9,31.862470,-106.547300
149,Ojo De Agua,12/2/2016,31,ug/m3 SC,29,31.862470,-106.547300
150,Ojo De Agua,12/14/2016,7,ug/m3 SC,6,31.862470,-106.547300
151,Ojo De Agua,12/26/2016,6,ug/m3 SC,6,31.862470,-106.547300

In [3]:
left = df_2016_PM
right = df_2016_NO
ElPaso_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer', indicator=True)

In [4]:
left = ElPaso_2016_All
right = df_2016_O
ElPaso_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [5]:
left = ElPaso_2016_All
right = df_2016_SO
ElPaso_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [6]:
left = ElPaso_2016_All
right = df_2016_CO
ElPaso_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [7]:
ElPaso_2016_All.columns

Index(['Site Name', 'Date', 'Daily Mean PM10 Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'SITE_LATITUDE', 'SITE_LONGITUDE',
       'Daily Max 1-hour NO2 Concentration', 'UNITS_y', 'DAILY_AQI_VALUE_y',
       '_merge', 'Daily Max 8-hour Ozone Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'Daily Max 1-hour SO2 Concentration', 'UNITS_y',
       'DAILY_AQI_VALUE_y', 'Daily Max 8-hour CO Concentration', 'UNITS',
       'DAILY_AQI_VALUE'],
      dtype='object')

In [8]:
ElPaso_2016_All.count()

Site Name                               2576
Date                                    2576
Daily Mean PM10 Concentration            152
UNITS_x                                  152
DAILY_AQI_VALUE_x                        152
SITE_LATITUDE                            152
SITE_LONGITUDE                           152
Daily Max 1-hour NO2 Concentration       972
UNITS_y                                  972
DAILY_AQI_VALUE_y                        972
_merge                                  1124
Daily Max 8-hour Ozone Concentration    2179
UNITS_x                                 2179
DAILY_AQI_VALUE_x                       2179
Daily Max 1-hour SO2 Concentration       874
UNITS_y                                  874
DAILY_AQI_VALUE_y                        874
Daily Max 8-hour CO Concentration        873
UNITS                                    873
DAILY_AQI_VALUE                          873
dtype: int64

In [9]:
#print(ElPaso_2016_All)

In [10]:
ElPaso_2016_All.columns=['Site Name','Date','DMean PM10','PM10 Units','PM10 AQI','Lat','Lng','DMax NO2','NO2 Units','NO2 AQI','Merged','DMax Ozone','Ozone Units','Ozone AQI','DMax SO2','SO2 Units','SO2 AQI','DMax CO','CO Units','CO AQI']

In [11]:
ElPaso_2016_All.count()

Site Name      2576
Date           2576
DMean PM10      152
PM10 Units      152
PM10 AQI        152
Lat             152
Lng             152
DMax NO2        972
NO2 Units       972
NO2 AQI         972
Merged         1124
DMax Ozone     2179
Ozone Units    2179
Ozone AQI      2179
DMax SO2        874
SO2 Units       874
SO2 AQI         874
DMax CO         873
CO Units        873
CO AQI          873
dtype: int64

In [12]:
ElPaso_2016_All.drop('Merged',axis=1,inplace=True)
ElPaso_2016_All.to_csv("EP2016DF.csv")

2018 Data

In [13]:
#files to load for 2018

ElPaso_CO_2018 = "CO-CarbonMonoxide/2018-ElPaso-CO.csv"
ElPaso_NO_2018 = "NitrogenDioxide/2018-ElPaso-NO2.csv"
ElPaso_O_2018 = "Ozone/2018-ElPaso-Ozone.csv"
ElPaso_PB_2018 = "PB-Lead/2018-ElPaso-PB.csv"
ElPaso_PM_2018 = "PM-ParticulateMatter/2018-ElPaso-PM10.csv"
ElPaso_SO_2018 = "SulfurDioxide/2018-ElPaso-SO2.csv"


#Read files into Pandas dataframe

df_2018_CO = pd.read_csv(ElPaso_CO_2018)
df_2018_NO = pd.read_csv(ElPaso_NO_2018)
df_2018_O = pd.read_csv(ElPaso_O_2018)
df_2018_PB = pd.read_csv(ElPaso_PB_2018)
df_2018_PM = pd.read_csv(ElPaso_PM_2018)
df_2018_SO = pd.read_csv(ElPaso_SO_2018)

df_2018_PM=df_2018_PM[['Site Name','Date','Daily Mean PM10 Concentration','UNITS','DAILY_AQI_VALUE', 'SITE_LATITUDE','SITE_LONGITUDE' ]]

df_2018_CO=df_2018_CO[['Site Name','Date','Daily Max 8-hour CO Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_NO=df_2018_NO[['Site Name','Date','Daily Max 1-hour NO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_O=df_2018_O[['Site Name','Date','Daily Max 8-hour Ozone Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_SO=df_2018_SO[['Site Name','Date','Daily Max 1-hour SO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_PB=df_2018_PB[['Site Name','Date','Daily Mean Pb Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_PM

,Site Name,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,SITE_LATITUDE,SITE_LONGITUDE
0,Ivanhoe,1/2/2018,14,ug/m3 SC,13,31.785769,-106.323578
1,Ivanhoe,1/8/2018,25,ug/m3 SC,23,31.785769,-106.323578
2,Ivanhoe,1/14/2018,15,ug/m3 SC,14,31.785769,-106.323578
3,Ivanhoe,1/20/2018,34,ug/m3 SC,31,31.785769,-106.323578
4,Ivanhoe,1/26/2018,21,ug/m3 SC,19,31.785769,-106.323578
...,...,...,...,...,...,...,...
374,Ojo De Agua,11/10/2018,19,ug/m3 SC,18,31.862470,-106.547300
375,Ojo De Agua,11/22/2018,34,ug/m3 SC,31,31.862470,-106.547300
376,Ojo De Agua,12/4/2018,23,ug/m3 SC,21,31.862470,-106.547300
377,Ojo De Agua,12/16/2018,35,ug/m3 SC,32,31.862470,-106.547300
378,Ojo De Agua,12/28/2018,0,ug/m3 SC,0,31.862470,-106.547300

In [14]:
ElPaso_2018_All=[]

In [15]:
left = df_2018_PM
right = df_2018_NO
ElPaso_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer', indicator=True)

In [16]:
left = ElPaso_2018_All
right = df_2018_O
ElPaso_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [17]:
left = ElPaso_2018_All
right = df_2018_SO
ElPaso_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [18]:
left = ElPaso_2018_All
right = df_2018_CO
ElPaso_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [19]:
ElPaso_2018_All.columns

Index(['Site Name', 'Date', 'Daily Mean PM10 Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'SITE_LATITUDE', 'SITE_LONGITUDE',
       'Daily Max 1-hour NO2 Concentration', 'UNITS_y', 'DAILY_AQI_VALUE_y',
       '_merge', 'Daily Max 8-hour Ozone Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'Daily Max 1-hour SO2 Concentration', 'UNITS_y',
       'DAILY_AQI_VALUE_y', 'Daily Max 8-hour CO Concentration', 'UNITS',
       'DAILY_AQI_VALUE'],
      dtype='object')

In [20]:
ElPaso_2018_All.count()

Site Name                               2719
Date                                    2719
Daily Mean PM10 Concentration            379
UNITS_x                                  379
DAILY_AQI_VALUE_x                        379
SITE_LATITUDE                            379
SITE_LONGITUDE                           379
Daily Max 1-hour NO2 Concentration       819
UNITS_y                                  819
DAILY_AQI_VALUE_y                        819
_merge                                  1198
Daily Max 8-hour Ozone Concentration    2194
UNITS_x                                 2194
DAILY_AQI_VALUE_x                       2194
Daily Max 1-hour SO2 Concentration        38
UNITS_y                                   38
DAILY_AQI_VALUE_y                         38
Daily Max 8-hour CO Concentration       1009
UNITS                                   1009
DAILY_AQI_VALUE                         1009
dtype: int64

In [21]:
ElPaso_2018_All.columns=['Site Name','Date','DMean PM10','PM10 Units','PM10 AQI','Lat','Lng','DMax NO2','NO2 Units','NO2 AQI','Merged','DMax Ozone','Ozone Units','Ozone AQI','DMax SO2','SO2 Units','SO2 AQI','DMax CO','CO Units','CO AQI']

In [22]:
ElPaso_2018_All.drop('Merged',axis=1,inplace=True)
ElPaso_2018_All.to_csv("EP2018DF.csv")

2020 Data

In [23]:
#files to load for 2020

ElPaso_CO_2020 = "CO-CarbonMonoxide/2020-ElPaso-CO.csv"
ElPaso_NO_2020 = "NitrogenDioxide/2020-ElPaso-NO2.csv"
ElPaso_O_2020 = "Ozone/2020-ElPaso-Ozone.csv"
ElPaso_PB_2020 = "PB-Lead/2020-ElPaso-PB.csv"
ElPaso_PM_2020 = "PM-ParticulateMatter/2020-ElPaso-PM10.csv"
ElPaso_SO_2020 = "SulfurDioxide/2020-ElPaso-SO2.csv"

#Read files into Pandas dataframe

df_2020_CO = pd.read_csv(ElPaso_CO_2020)
df_2020_NO = pd.read_csv(ElPaso_NO_2020)
df_2020_O = pd.read_csv(ElPaso_O_2020)
df_2020_PB = pd.read_csv(ElPaso_PB_2020)
df_2020_PM = pd.read_csv(ElPaso_PM_2020)
df_2020_SO = pd.read_csv(ElPaso_SO_2020)


df_2020_PM=df_2020_PM[['Site Name','Date','Daily Mean PM10 Concentration','UNITS','DAILY_AQI_VALUE', 'SITE_LATITUDE','SITE_LONGITUDE' ]]

df_2020_CO=df_2020_CO[['Site Name','Date','Daily Max 8-hour CO Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_NO=df_2020_NO[['Site Name','Date','Daily Max 1-hour NO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_O=df_2020_O[['Site Name','Date','Daily Max 8-hour Ozone Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_SO=df_2020_SO[['Site Name','Date','Daily Max 1-hour SO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_PB=df_2020_PB[['Site Name','Date','Daily Mean Pb Concentration','UNITS','DAILY_AQI_VALUE']]


df_2020_PM

,Site Name,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,SITE_LATITUDE,SITE_LONGITUDE
0,Ivanhoe,1/4/2020,37,ug/m3 SC,34,31.785769,-106.323578
1,Ivanhoe,1/10/2020,8,ug/m3 SC,7,31.785769,-106.323578
2,Ivanhoe,1/16/2020,20,ug/m3 SC,19,31.785769,-106.323578
3,Ivanhoe,1/22/2020,8,ug/m3 SC,7,31.785769,-106.323578
4,Ivanhoe,1/28/2020,12,ug/m3 SC,11,31.785769,-106.323578
...,...,...,...,...,...,...,...
313,Ojo De Agua,11/11/2020,14,ug/m3 SC,13,31.862470,-106.547300
314,Ojo De Agua,11/23/2020,45,ug/m3 SC,42,31.862470,-106.547300
315,Ojo De Agua,12/5/2020,28,ug/m3 SC,26,31.862470,-106.547300
316,Ojo De Agua,12/17/2020,28,ug/m3 SC,26,31.862470,-106.547300
317,Ojo De Agua,12/29/2020,11,ug/m3 SC,10,31.862470,-106.547300

In [24]:
ElPaso_2020_All = []

In [25]:
left = df_2020_PM
right = df_2020_NO
ElPaso_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer', indicator=True)

In [26]:
left = ElPaso_2020_All
right = df_2020_O
ElPaso_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [27]:
left = ElPaso_2020_All
right = df_2020_SO
ElPaso_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [28]:
left = ElPaso_2020_All
right = df_2020_CO
ElPaso_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [29]:
ElPaso_2020_All.count()

Site Name                               2663
Date                                    2663
Daily Mean PM10 Concentration            318
UNITS_x                                  318
DAILY_AQI_VALUE_x                        318
SITE_LATITUDE                            318
SITE_LONGITUDE                           318
Daily Max 1-hour NO2 Concentration       985
UNITS_y                                  985
DAILY_AQI_VALUE_y                        985
_merge                                  1303
Daily Max 8-hour Ozone Concentration    2169
UNITS_x                                 2169
DAILY_AQI_VALUE_x                       2169
Daily Max 1-hour SO2 Concentration       349
UNITS_y                                  349
DAILY_AQI_VALUE_y                        349
Daily Max 8-hour CO Concentration       1024
UNITS                                   1024
DAILY_AQI_VALUE                         1024
dtype: int64

In [30]:
ElPaso_2020_All.tail()

,Site Name,Date,Daily Mean PM10 Concentration,UNITS_x,DAILY_AQI_VALUE_x,SITE_LATITUDE,SITE_LONGITUDE,Daily Max 1-hour NO2 Concentration,UNITS_y,DAILY_AQI_VALUE_y,_merge,Daily Max 8-hour Ozone Concentration,UNITS_x,DAILY_AQI_VALUE_x,Daily Max 1-hour SO2 Concentration,UNITS_y,DAILY_AQI_VALUE_y,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE
2658,Ojo De Agua,12/26/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2659,Ojo De Agua,12/27/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2660,Ojo De Agua,12/28/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,ppm,6.0
2661,Ojo De Agua,12/30/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2662,Ojo De Agua,12/31/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0

In [31]:
ElPaso_2020_All.columns=['Site Name','Date','DMean PM10','PM10 Units','PM10 AQI','Lat','Lng','DMax NO2','NO2 Units','NO2 AQI','Merged','DMax Ozone','Ozone Units','Ozone AQI','DMax SO2','SO2 Units','SO2 AQI','DMax CO','CO Units','CO AQI']

In [32]:
ElPaso_2020_All.columns

Index(['Site Name', 'Date', 'DMean PM10', 'PM10 Units', 'PM10 AQI', 'Lat',
       'Lng', 'DMax NO2', 'NO2 Units', 'NO2 AQI', 'Merged', 'DMax Ozone',
       'Ozone Units', 'Ozone AQI', 'DMax SO2', 'SO2 Units', 'SO2 AQI',
       'DMax CO', 'CO Units', 'CO AQI'],
      dtype='object')

In [33]:
ElPaso_2020_All.drop('Merged',axis=1,inplace=True)
ElPaso_2020_All.to_csv("EP2020DF.csv")