In [1]:
import pandas as pd
import io
from io import StringIO

READ THE CSV AND PERFORM BASIC DATA CLEANING

In [2]:
df_01 = pd.read_csv("EP2016DF.csv")
#print(df_01.count())
#print(df_01)
#drop the null rows
#df_01 = df_01.dropna()
#print(df_01.count())
print(df_01['Site Name'].unique())

['Ivanhoe' 'El Paso Mimosa' 'Socorro Hueco' 'Van Buren' 'Ojo De Agua'
 'El Paso UTEP' 'El Paso Chamizal' 'Ascarate Park SE' 'Skyline Park']

In [3]:
#print(df_01.head())
#pd.read_csv(io.StringIO(df_01.to_csv(index=False)))
test_df=df_01.iloc[:,1:]
test_df

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Ivanhoe,10/27/2016,16.0,ug/m3 SC,15.0,31.785769,-106.323578,NaN,NaN,NaN,0.038,ppm,35.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Ivanhoe,11/2/2016,13.0,ug/m3 SC,12.0,31.785769,-106.323578,NaN,NaN,NaN,0.024,ppm,22.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Ivanhoe,11/8/2016,7.0,ug/m3 SC,6.0,31.785769,-106.323578,NaN,NaN,NaN,0.036,ppm,33.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Ivanhoe,11/14/2016,25.0,ug/m3 SC,23.0,31.785769,-106.323578,NaN,NaN,NaN,0.038,ppm,35.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Ivanhoe,11/20/2016,18.0,ug/m3 SC,17.0,31.785769,-106.323578,NaN,NaN,NaN,0.032,ppm,30.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2571,Ojo De Agua,12/25/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2572,Ojo De Agua,12/27/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2573,Ojo De Agua,12/28/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2574,Ojo De Agua,12/29/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2575,Ojo De Agua,12/30/2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0

In [4]:
df_02 = pd.read_csv("EP2018DF.csv")
#print(df_02.count())
#drop the null rows
#df_02 = df_02.dropna()
#print(df_02['Site Name'].unique())

In [5]:
#print(df_02.head())
#pd.read_csv(io.StringIO(df_01.to_csv(index=False)))
test2_df=df_02.iloc[:,1:]
test2_df

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Ivanhoe,1/2/2018,14.0,ug/m3 SC,13.0,31.785769,-106.323578,NaN,NaN,NaN,0.030,ppm,28.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Ivanhoe,1/8/2018,25.0,ug/m3 SC,23.0,31.785769,-106.323578,NaN,NaN,NaN,0.031,ppm,29.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Ivanhoe,1/14/2018,15.0,ug/m3 SC,14.0,31.785769,-106.323578,NaN,NaN,NaN,0.038,ppm,35.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Ivanhoe,1/20/2018,34.0,ug/m3 SC,31.0,31.785769,-106.323578,NaN,NaN,NaN,0.034,ppm,31.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Ivanhoe,1/26/2018,21.0,ug/m3 SC,19.0,31.785769,-106.323578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2714,Ojo De Agua,12/26/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,ppm,6.0
2715,Ojo De Agua,12/27/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2716,Ojo De Agua,12/29/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2717,Ojo De Agua,12/30/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2718,Ojo De Agua,12/31/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0

In [7]:
df_03 = pd.read_csv("EP2020DF.csv")
#print(df_01.count())
#drop the null rows
#df_03 = df_03.dropna()
print(df_03['Site Name'].unique())

['Ivanhoe' 'El Paso Mimosa' 'Socorro Hueco' 'Van Buren' 'Ojo De Agua'
 'El Paso UTEP' 'El Paso Chamizal' 'Ascarate Park SE' 'Skyline Park']

In [8]:
#print(df_03.head())
#pd.read_csv(io.StringIO(df_01.to_csv(index=False)))
test3_df=df_03.iloc[:,1:]
test3_df

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Ivanhoe,1/4/2020,37.0,ug/m3 SC,34.0,31.785769,-106.323578,NaN,NaN,NaN,0.028,ppm,26.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Ivanhoe,1/10/2020,8.0,ug/m3 SC,7.0,31.785769,-106.323578,NaN,NaN,NaN,0.039,ppm,36.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Ivanhoe,1/16/2020,20.0,ug/m3 SC,19.0,31.785769,-106.323578,NaN,NaN,NaN,0.022,ppm,20.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Ivanhoe,1/22/2020,8.0,ug/m3 SC,7.0,31.785769,-106.323578,NaN,NaN,NaN,0.035,ppm,32.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Ivanhoe,1/28/2020,12.0,ug/m3 SC,11.0,31.785769,-106.323578,NaN,NaN,NaN,0.041,ppm,38.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2658,Ojo De Agua,12/26/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2659,Ojo De Agua,12/27/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2660,Ojo De Agua,12/28/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,ppm,6.0
2661,Ojo De Agua,12/30/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2662,Ojo De Agua,12/31/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0

In [9]:
AllData=pd.DataFrame()
AllData=AllData.append(test_df)

In [10]:
AllData=AllData.append(test2_df)

In [11]:
AllData=AllData.append(test3_df)

In [12]:
AllData.to_csv("EPMerged.csv")

In [13]:
AllData

,Site Name,Date,DMean PM10,PM10 Units,PM10 AQI,Lat,Lng,DMax NO2,NO2 Units,NO2 AQI,DMax Ozone,Ozone Units,Ozone AQI,DMax SO2,SO2 Units,SO2 AQI,DMax CO,CO Units,CO AQI
0,Ivanhoe,10/27/2016,16.0,ug/m3 SC,15.0,31.785769,-106.323578,NaN,NaN,NaN,0.038,ppm,35.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Ivanhoe,11/2/2016,13.0,ug/m3 SC,12.0,31.785769,-106.323578,NaN,NaN,NaN,0.024,ppm,22.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Ivanhoe,11/8/2016,7.0,ug/m3 SC,6.0,31.785769,-106.323578,NaN,NaN,NaN,0.036,ppm,33.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Ivanhoe,11/14/2016,25.0,ug/m3 SC,23.0,31.785769,-106.323578,NaN,NaN,NaN,0.038,ppm,35.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Ivanhoe,11/20/2016,18.0,ug/m3 SC,17.0,31.785769,-106.323578,NaN,NaN,NaN,0.032,ppm,30.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2658,Ojo De Agua,12/26/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
2659,Ojo De Agua,12/27/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2660,Ojo De Agua,12/28/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,ppm,6.0
2661,Ojo De Agua,12/30/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0
2662,Ojo De Agua,12/31/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,ppm,2.0