In [1]:
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

2016 Data

In [2]:
#files to load for 2016
LA_CO_2016 = "CO-CarbonMonoxide/2016-LA-CO.csv"
LA_NO_2016 = "NitrogenDioxide/2016-LA-NO2.csv"
LA_O_2016 = "Ozone/2016-LA-Ozone.csv"
LA_PB_2016 = "PB-Lead/2016-LA-PB.csv"
LA_PM_2016 = "PM-ParticulateMatter/2016-LA-PM10.csv"
LA_SO_2016 = "SulfurDioxide/2016-LA-SO2.csv"

#Read files into Pandas dataframe

df_2016_CO = pd.read_csv(LA_CO_2016)
df_2016_NO = pd.read_csv(LA_NO_2016)
df_2016_O = pd.read_csv(LA_O_2016)
df_2016_PB = pd.read_csv(LA_PB_2016)
df_2016_PM = pd.read_csv(LA_PM_2016)
df_2016_SO = pd.read_csv(LA_SO_2016)


df_2016_PM=df_2016_PM[['Site Name','Date','Daily Mean PM10 Concentration','UNITS','DAILY_AQI_VALUE', 'SITE_LATITUDE','SITE_LONGITUDE' ]]

df_2016_CO=df_2016_CO[['Site Name','Date','Daily Max 8-hour CO Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_NO=df_2016_NO[['Site Name','Date','Daily Max 1-hour NO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_O=df_2016_O[['Site Name','Date','Daily Max 8-hour Ozone Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_SO=df_2016_SO[['Site Name','Date','Daily Max 1-hour SO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2016_PB=df_2016_PB[['Site Name','Date','Daily Mean Pb Concentration','UNITS','DAILY_AQI_VALUE']]


df_2016_PM

,Site Name,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,SITE_LATITUDE,SITE_LONGITUDE
0,Azusa,1/1/2016,12,ug/m3 SC,11,34.13650,-117.92391
1,Azusa,1/7/2016,7,ug/m3 SC,6,34.13650,-117.92391
2,Azusa,1/13/2016,32,ug/m3 SC,30,34.13650,-117.92391
3,Azusa,1/19/2016,24,ug/m3 SC,22,34.13650,-117.92391
4,Azusa,1/25/2016,16,ug/m3 SC,15,34.13650,-117.92391
...,...,...,...,...,...,...,...
1545,Mission Viejo,12/2/2016,45,ug/m3 SC,42,33.63003,-117.67593
1546,Mission Viejo,12/8/2016,26,ug/m3 SC,24,33.63003,-117.67593
1547,Mission Viejo,12/14/2016,39,ug/m3 SC,36,33.63003,-117.67593
1548,Mission Viejo,12/20/2016,16,ug/m3 SC,15,33.63003,-117.67593
1549,Mission Viejo,12/26/2016,12,ug/m3 SC,11,33.63003,-117.67593

In [3]:
left = df_2016_PM
right = df_2016_NO
LA_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer', indicator=True)

In [4]:
left = LA_2016_All
right = df_2016_O
LA_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [5]:
left = LA_2016_All
right = df_2016_SO
LA_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [6]:
left = LA_2016_All
right = df_2016_CO
LA_2016_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [7]:
LA_2016_All.columns

Index(['Site Name', 'Date', 'Daily Mean PM10 Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'SITE_LATITUDE', 'SITE_LONGITUDE',
       'Daily Max 1-hour NO2 Concentration', 'UNITS_y', 'DAILY_AQI_VALUE_y',
       '_merge', 'Daily Max 8-hour Ozone Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'Daily Max 1-hour SO2 Concentration', 'UNITS_y',
       'DAILY_AQI_VALUE_y', 'Daily Max 8-hour CO Concentration', 'UNITS',
       'DAILY_AQI_VALUE'],
      dtype='object')

In [8]:
LA_2016_All.count()

Site Name                               7247
Date                                    7247
Daily Mean PM10 Concentration           1597
UNITS_x                                 1597
DAILY_AQI_VALUE_x                       1597
SITE_LATITUDE                           1597
SITE_LONGITUDE                          1597
Daily Max 1-hour NO2 Concentration      6689
UNITS_y                                 6689
DAILY_AQI_VALUE_y                       6689
_merge                                  6845
Daily Max 8-hour Ozone Concentration    6311
UNITS_x                                 6311
DAILY_AQI_VALUE_x                       6311
Daily Max 1-hour SO2 Concentration      1707
UNITS_y                                 1707
DAILY_AQI_VALUE_y                       1707
Daily Max 8-hour CO Concentration       6561
UNITS                                   6561
DAILY_AQI_VALUE                         6561
dtype: int64

In [9]:
#print(ElPaso_2016_All)

In [10]:
LA_2016_All.columns=['Site Name','Date','DMean PM10','PM10 Units','PM10 AQI','Lat','Lng','DMax NO2','NO2 Units','NO2 AQI','Merged','DMax Ozone','Ozone Units','Ozone AQI','DMax SO2','SO2 Units','SO2 AQI','DMax CO','CO Units','CO AQI']

In [11]:
LA_2016_All.count()

Site Name      7247
Date           7247
DMean PM10     1597
PM10 Units     1597
PM10 AQI       1597
Lat            1597
Lng            1597
DMax NO2       6689
NO2 Units      6689
NO2 AQI        6689
Merged         6845
DMax Ozone     6311
Ozone Units    6311
Ozone AQI      6311
DMax SO2       1707
SO2 Units      1707
SO2 AQI        1707
DMax CO        6561
CO Units       6561
CO AQI         6561
dtype: int64

In [12]:
LA_2016_All.drop('Merged',axis=1,inplace=True)
LA_2016_All.to_csv("LA2016DF.csv")

2018 Data

In [13]:
#files to load for 2018

LA_CO_2018 = "CO-CarbonMonoxide/2018-LA-CO.csv"
LA_NO_2018 = "NitrogenDioxide/2018-LA-NO2.csv"
LA_O_2018 = "Ozone/2018-LA-Ozone.csv"
LA_PB_2018 = "PB-Lead/2018-LA-PB.csv"
LA_PM_2018 = "PM-ParticulateMatter/2018-LA-PM10.csv"
LA_SO_2018 = "SulfurDioxide/2018-LA-SO2.csv"


#Read files into Pandas dataframe

df_2018_CO = pd.read_csv(LA_CO_2018)
df_2018_NO = pd.read_csv(LA_NO_2018)
df_2018_O = pd.read_csv(LA_O_2018)
df_2018_PB = pd.read_csv(LA_PB_2018)
df_2018_PM = pd.read_csv(LA_PM_2018)
df_2018_SO = pd.read_csv(LA_SO_2018)

df_2018_PM=df_2018_PM[['Site Name','Date','Daily Mean PM10 Concentration','UNITS','DAILY_AQI_VALUE', 'SITE_LATITUDE','SITE_LONGITUDE' ]]

df_2018_CO=df_2018_CO[['Site Name','Date','Daily Max 8-hour CO Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_NO=df_2018_NO[['Site Name','Date','Daily Max 1-hour NO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_O=df_2018_O[['Site Name','Date','Daily Max 8-hour Ozone Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_SO=df_2018_SO[['Site Name','Date','Daily Max 1-hour SO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_PB=df_2018_PB[['Site Name','Date','Daily Mean Pb Concentration','UNITS','DAILY_AQI_VALUE']]

df_2018_PM

,Site Name,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,SITE_LATITUDE,SITE_LONGITUDE
0,Azusa,1/2/2018,78,ug/m3 SC,62,34.13650,-117.92391
1,Azusa,1/8/2018,14,ug/m3 SC,13,34.13650,-117.92391
2,Azusa,1/14/2018,10,ug/m3 SC,9,34.13650,-117.92391
3,Azusa,1/20/2018,13,ug/m3 SC,12,34.13650,-117.92391
4,Azusa,1/26/2018,16,ug/m3 SC,15,34.13650,-117.92391
...,...,...,...,...,...,...,...
1462,Mission Viejo,12/4/2018,12,ug/m3 SC,11,33.63003,-117.67593
1463,Mission Viejo,12/10/2018,22,ug/m3 SC,20,33.63003,-117.67593
1464,Mission Viejo,12/16/2018,22,ug/m3 SC,20,33.63003,-117.67593
1465,Mission Viejo,12/22/2018,30,ug/m3 SC,28,33.63003,-117.67593
1466,Mission Viejo,12/28/2018,11,ug/m3 SC,10,33.63003,-117.67593

In [14]:
LA_2018_All=[]

In [15]:
left = df_2018_PM
right = df_2018_NO
LA_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer', indicator=True)

In [16]:
left = LA_2018_All
right = df_2018_O
LA_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [17]:
left = LA_2018_All
right = df_2018_SO
LA_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [18]:
left = LA_2018_All
right = df_2018_CO
LA_2018_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [19]:
LA_2018_All.columns

Index(['Site Name', 'Date', 'Daily Mean PM10 Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'SITE_LATITUDE', 'SITE_LONGITUDE',
       'Daily Max 1-hour NO2 Concentration', 'UNITS_y', 'DAILY_AQI_VALUE_y',
       '_merge', 'Daily Max 8-hour Ozone Concentration', 'UNITS_x',
       'DAILY_AQI_VALUE_x', 'Daily Max 1-hour SO2 Concentration', 'UNITS_y',
       'DAILY_AQI_VALUE_y', 'Daily Max 8-hour CO Concentration', 'UNITS',
       'DAILY_AQI_VALUE'],
      dtype='object')

In [20]:
LA_2018_All.count()

Site Name                               6907
Date                                    6907
Daily Mean PM10 Concentration           1506
UNITS_x                                 1506
DAILY_AQI_VALUE_x                       1506
SITE_LATITUDE                           1506
SITE_LONGITUDE                          1506
Daily Max 1-hour NO2 Concentration      6177
UNITS_y                                 6177
DAILY_AQI_VALUE_y                       6177
_merge                                  6327
Daily Max 8-hour Ozone Concentration    5930
UNITS_x                                 5930
DAILY_AQI_VALUE_x                       5930
Daily Max 1-hour SO2 Concentration      1324
UNITS_y                                 1324
DAILY_AQI_VALUE_y                       1324
Daily Max 8-hour CO Concentration       6351
UNITS                                   6351
DAILY_AQI_VALUE                         6351
dtype: int64

In [21]:
LA_2018_All.columns=['Site Name','Date','DMean PM10','PM10 Units','PM10 AQI','Lat','Lng','DMax NO2','NO2 Units','NO2 AQI','Merged','DMax Ozone','Ozone Units','Ozone AQI','DMax SO2','SO2 Units','SO2 AQI','DMax CO','CO Units','CO AQI']

In [22]:
LA_2018_All.drop('Merged',axis=1,inplace=True)
LA_2018_All.to_csv("LA2018DF.csv")

2020 Data

In [23]:
#files to load for 2020

LA_CO_2020 = "CO-CarbonMonoxide/2020-LA-CO.csv"
LA_NO_2020 = "NitrogenDioxide/2020-LA-NO2.csv"
LA_O_2020 = "Ozone/2020-LA-Ozone.csv"
LA_PB_2020 = "PB-Lead/2020-LA-PB.csv"
LA_PM_2020 = "PM-ParticulateMatter/2020-LA-PM10.csv"
LA_SO_2020 = "SulfurDioxide/2020-LA-SO2.csv"

#Read files into Pandas dataframe

df_2020_CO = pd.read_csv(LA_CO_2020)
df_2020_NO = pd.read_csv(LA_NO_2020)
df_2020_O = pd.read_csv(LA_O_2020)
df_2020_PB = pd.read_csv(LA_PB_2020)
df_2020_PM = pd.read_csv(LA_PM_2020)
df_2020_SO = pd.read_csv(LA_SO_2020)


df_2020_PM=df_2020_PM[['Site Name','Date','Daily Mean PM10 Concentration','UNITS','DAILY_AQI_VALUE', 'SITE_LATITUDE','SITE_LONGITUDE' ]]

df_2020_CO=df_2020_CO[['Site Name','Date','Daily Max 8-hour CO Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_NO=df_2020_NO[['Site Name','Date','Daily Max 1-hour NO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_O=df_2020_O[['Site Name','Date','Daily Max 8-hour Ozone Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_SO=df_2020_SO[['Site Name','Date','Daily Max 1-hour SO2 Concentration','UNITS','DAILY_AQI_VALUE']]

df_2020_PB=df_2020_PB[['Site Name','Date','Daily Mean Pb Concentration','UNITS','DAILY_AQI_VALUE']]


df_2020_PM

,Site Name,Date,Daily Mean PM10 Concentration,UNITS,DAILY_AQI_VALUE,SITE_LATITUDE,SITE_LONGITUDE
0,Azusa,1/4/2020,25,ug/m3 SC,23,34.13650,-117.92391
1,Azusa,1/10/2020,20,ug/m3 SC,19,34.13650,-117.92391
2,Azusa,1/16/2020,32,ug/m3 SC,30,34.13650,-117.92391
3,Azusa,1/22/2020,21,ug/m3 SC,19,34.13650,-117.92391
4,Azusa,1/28/2020,23,ug/m3 SC,21,34.13650,-117.92391
...,...,...,...,...,...,...,...
1382,Mission Viejo,12/5/2020,16,ug/m3 SC,15,33.63003,-117.67593
1383,Mission Viejo,12/11/2020,17,ug/m3 SC,16,33.63003,-117.67593
1384,Mission Viejo,12/17/2020,11,ug/m3 SC,10,33.63003,-117.67593
1385,Mission Viejo,12/23/2020,22,ug/m3 SC,20,33.63003,-117.67593
1386,Mission Viejo,12/29/2020,4,ug/m3 SC,4,33.63003,-117.67593

In [24]:
LA_2020_All = []

In [25]:
left = df_2020_PM
right = df_2020_NO
LA_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer', indicator=True)

In [26]:
left = LA_2020_All
right = df_2020_O
LA_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [27]:
left = LA_2020_All
right = df_2020_SO
LA_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [28]:
left = LA_2020_All
right = df_2020_CO
LA_2020_All = pd.merge(left, right, on=['Site Name','Date'],how='outer')

In [29]:
LA_2020_All.count()

Site Name                               7782
Date                                    7782
Daily Mean PM10 Concentration           1470
UNITS_x                                 1470
DAILY_AQI_VALUE_x                       1470
SITE_LATITUDE                           1470
SITE_LONGITUDE                          1470
Daily Max 1-hour NO2 Concentration      7271
UNITS_y                                 7271
DAILY_AQI_VALUE_y                       7271
_merge                                  7392
Daily Max 8-hour Ozone Concentration    6849
UNITS_x                                 6849
DAILY_AQI_VALUE_x                       6849
Daily Max 1-hour SO2 Concentration      1393
UNITS_y                                 1393
DAILY_AQI_VALUE_y                       1393
Daily Max 8-hour CO Concentration       6582
UNITS                                   6582
DAILY_AQI_VALUE                         6582
dtype: int64

In [30]:
LA_2020_All.tail()

,Site Name,Date,Daily Mean PM10 Concentration,UNITS_x,DAILY_AQI_VALUE_x,SITE_LATITUDE,SITE_LONGITUDE,Daily Max 1-hour NO2 Concentration,UNITS_y,DAILY_AQI_VALUE_y,_merge,Daily Max 8-hour Ozone Concentration,UNITS_x,DAILY_AQI_VALUE_x,Daily Max 1-hour SO2 Concentration,UNITS_y,DAILY_AQI_VALUE_y,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE
7777,Mission Viejo,2/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,ppm,5.0
7778,La Habra,1/27/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8,ppm,9.0
7779,La Habra,3/10/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,ppm,1.0
7780,La Habra,6/11/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3,ppm,3.0
7781,La Habra,7/13/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,ppm,1.0

In [31]:
LA_2020_All.columns=['Site Name','Date','DMean PM10','PM10 Units','PM10 AQI','Lat','Lng','DMax NO2','NO2 Units','NO2 AQI','Merged','DMax Ozone','Ozone Units','Ozone AQI','DMax SO2','SO2 Units','SO2 AQI','DMax CO','CO Units','CO AQI']

In [32]:
LA_2020_All.columns

Index(['Site Name', 'Date', 'DMean PM10', 'PM10 Units', 'PM10 AQI', 'Lat',
       'Lng', 'DMax NO2', 'NO2 Units', 'NO2 AQI', 'Merged', 'DMax Ozone',
       'Ozone Units', 'Ozone AQI', 'DMax SO2', 'SO2 Units', 'SO2 AQI',
       'DMax CO', 'CO Units', 'CO AQI'],
      dtype='object')

In [33]:
LA_2020_All.drop('Merged',axis=1,inplace=True)
LA_2020_All.to_csv("LA2020DF.csv")